packages:
  - front-end
  - web-server
  - game-server
  - discord-service
  - shared
  - shared/database

configDependencies:
  "@pnpm/plugin-types-fixer": 0.1.0+sha512-bLww63gRHi7siYTqFJb5qNdcXadU0jv20Et6z5AryMZ7FlLolbEJOrXLpg8+amQZNHHNW1dfFUBGVw/9ezQbFg==

linkWorkspacePackages: true
